export const ROLES = ["ADMIN", "TEACHER", "PARENT", "STUDENT"] as const;
export type Role = (typeof ROLES)[number];

export const PERMISSIONS = {
  STUDENT_VIEW_SELF: "STUDENT_VIEW_SELF",
  ATTENDANCE_VIEW_SELF: "ATTENDANCE_VIEW_SELF",
  RESULT_VIEW_SELF: "RESULT_VIEW_SELF",
  FEE_VIEW_SELF: "FEE_VIEW_SELF",
  TEACHER_VIEW_ASSIGNED_CLASS: "TEACHER_VIEW_ASSIGNED_CLASS",
  ATTENDANCE_CREATE: "ATTENDANCE_CREATE",
  ATTENDANCE_UPDATE: "ATTENDANCE_UPDATE",
  MARKS_CREATE: "MARKS_CREATE",
  MARKS_UPDATE: "MARKS_UPDATE",
  ADMIN_STUDENT_CREATE: "ADMIN_STUDENT_CREATE",
  ADMIN_STUDENT_UPDATE: "ADMIN_STUDENT_UPDATE",
  ADMIN_FEES_MANAGE: "ADMIN_FEES_MANAGE",
  ADMIN_EXAMS_MANAGE: "ADMIN_EXAMS_MANAGE",
  ADMIN_NOTICES_CREATE: "ADMIN_NOTICES_CREATE",
} as const;
